### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by l3CY** [K-4U/pvpToggle#4]
Hello, 
Game is unable to startup after adding pvpToggle.
Here is my crash log. http://pastebin.com/2HiKQd65

Forge: 10.13.3.1408
pvpToggle: 1.7.10-1.0.31

I'm not sure what more info I could provide, but if there is anything more then just ask.

**Comment by K-4U** [comment]
Install latest K4Lib

**Comment by l3CY** [comment]
Thank you.  You may want to post this requirement on the curse download page.
