### ISSUE TITLE
Keeping experience after PvP death, not working

### ISSUE THREAD

**Issue by xrampagex** [K-4U/pvpToggle#5]
A friend and I tested out PvPToggle, and keeping experience after PvP death isn't working.

On the client and server, it is set to: B:keepExperienceOnPVPDeath=true

Using Forge: 10-10.13.4.1448 and Fastcraft.

There are no errors.

Not a high priority issue, just a minor annoyance.

**Comment by K-4U** [comment]
I'm really sorry for my late reply on this. Are you still experiencing this issue with later builds?
