### ISSUE TITLE
PVPToggle Not Working

### ISSUE THREAD

**Issue by O13SC3N3** [K-4U/pvpToggle#7]
Players unable to attack each other even with both of them set with /pvp on.

Minecraft 1.7.10 forge 1556

Also trying to make all dimensions pvp open besides Over world this possible?

**Comment by K-4U** [comment]
What version of pvptoggle are you running?

What do you mean by "pvp open"?

**Comment by O13SC3N3** [comment]
forge 1558
latest version from curse plus library.
and was trying to make other dimensions pvp on irregardless of the users choice, but still give them the option to choose in the overworld. Also noticed when both players turn off pvptoggle to fight they still cant hurt each other... There are no other mods that mess with this fact.

**Comment by K-4U** [comment]
Does it show the message in chat that both players need pvp enabled?

**Comment by O13SC3N3** [comment]
yes

**Comment by O13SC3N3** [comment]
Am I doing something wrong here? Is it a server setting? Or is this an actual bug because I can't seem to get this to work. The symbols and the ability to change pvp on off works for everyone just even if enabled nobody can kill each other. And dimensions don't seem to recognized forced pvp etc.

**Comment by LabGoblin** [comment]
i may also be having the same issue on pvpToggle v1.0.11 on forge 1724

**Comment by K-4U** [comment]
Is there any stacktrace or anything if one of the players changes their PVP status?

**Comment by O13SC3N3** [comment]
No it all seems to work fine, just its like it doesn't register them being killable by another pvper now. Both client and server have the mod installed. Everything seems to work as intended, well except the dimension thing I cant seem to figure it out.

Any player can pvp on or off at will, cant hurt each other in either mod. just says "Both players need to be pvp enabeled" or something like that.

**Comment by K-4U** [comment]
Do you have PVP enabled in the server config?

**Comment by O13SC3N3** [comment]
In the server properties yes

**Comment by O13SC3N3** [comment]
Any ideas m8?

Also I noticed the ICON gui doesnt seem to stay fixed with different resolutions. Anyways to adapt this to the screens points top left top right etc etc etc... So that way if other users have other huds active we can position them accordingly so doesnt matter when users in LARGE, NORMAL, or SMALL the pvp icon will stay in perspective.

**Comment by K-4U** [comment]
With regards to the icon, there's already an issue open for that, i hope to fix that asap.
With regards to the pvp not working, i'm really unsure as to what's causing it, but i have a feeling that there may be an intermod issue.

I did never see which version of PvPToggle you're running.

**Comment by O13SC3N3** [comment]
pvpToggle-1.7.10-1.0.33-universal.jar

**Comment by K-4U** [comment]
Do the players see eachother (and themselves) have PvP enabled? (icon in top left corner + icon over their heads)

**Comment by O13SC3N3** [comment]
Yes sir, we experimented a lot with it actually
