### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by yepidoodles** [K-4U/pvpToggle#8]
I've gotten this same crash with both 1.9.4 and now 1.10.2 on my server

http://www.codesend.com/view/7277be4996fe02fe6fc6d2bf8976dc64/

**Comment by K-4U** [comment]
So yeah, massively late reply.. But did you install K4Lib?

**Comment by yepidoodles** [comment]
I have no idea, I ended up using a plugin.

**Comment by K-4U** [comment]
Shame. If you ever get around to using it, make sure you have K4Lib installed ;)
